GmailMessagesViewer/Models/MessageInfoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GmailMessagesViewer.Models
{
    public class MessageInfoViewModel
    {
        public string Id { get; set; }
        public string Title { get; set; }
    }
}

GmailMessagesViewer/Models/MessagesListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GmailMessagesViewer.Models
{
    public class MessagesListViewModel
    {
        public Pagination Pagination { get; set; }
        public List<MessageInfoViewModel> Messages { get; set; }
    }
}

GmailMessagesViewer/Models/Pagination.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GmailMessagesViewer.Models
{
    public class Pagination
    {
        public int PageNumber { get; set; }
        public int PageSize { get; set; }
        public int TotalItemsCount { get; set; }
        public int TotalPagesCount
        {
            get
            {
                return (int)Math.Ceiling((decimal)TotalItemsCount/ PageSize);
            }
        }
    }
}

GmailMessagesViewer/Controllers/AuthController.cs
using GmailMessagesViewer.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GmailMessagesViewer.Controllers
{
    public class AuthController : Controller
    {
        public ActionResult ChangeUser()
        {
            AuthService.RemoveCredentials(this);
            return RedirectToAction("GetMessages", "Messages");
        }
    }
}

GmailMessagesViewer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GmailMessagesViewer.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

GmailMessagesViewer/Controllers/MessagesController.cs
using GmailMessagesViewer.Filters;
using GmailMessagesViewer.Models;
using GmailMessagesViewer.Services;
using Google.Apis.Auth.OAuth2;
using Google.Apis.Gmail.v1;
using Google.Apis.Gmail.v1.Data;
using Google.Apis.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GmailMessagesViewer.Controllers
{
    [UserSession]
    public class MessagesController : Controller
    {
        private GmailService service;
        private static UserCredential credential;
        private static string ApplicationName = "GetMessagesApp";

        public MessagesController()
        {
            credential = AuthService.CreateCredentials(this);
            service = new GmailService(new BaseClientService.Initializer()
            {
                HttpClientInitializer = credential,
                ApplicationName = ApplicationName,
            });
        }

        // GET: Messages
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetMessages(int pageNumber=1)
        {
            int pageSize = 10;
            var messages = MessageService.GetMessagesList(service, "me");
            var totalMessagesCount = messages.Count;

            messages = messages
                .Skip((pageSize - 1) * pageNumber)
                .Take(pageSize)
                .ToList();

            var viewModel = new MessagesListViewModel()
            {
                Messages = new List<MessageInfoViewModel>(),
                Pagination = new Pagination()
                {
                    PageSize = pageSize,
                    PageNumber = pageNumber,
                    TotalItemsCount = totalMessagesCount
                }
            };

            foreach (var mes in messages)
            {
                Message message = MessageService.GetMessage(service, "me", mes.Id);
                viewModel.Messages.Add(new MessageInfoViewModel
                {
                    Id = message.Id,
                    Title = message.Snippet
                });
            }

            return View(viewModel);
        }
        public ActionResult ChangeUser()
        {
            AuthService.RemoveCredentials(this);
            return RedirectToAction("GetMessages");
        }
    }
}

GmailMessagesViewer/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

GmailMessagesViewer/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

GmailMessagesViewer/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

GmailMessagesViewer/Views/Messages/GetMessages.cshtml
@model GmailMessagesViewer.Models.MessagesListViewModel

@{
    ViewBag.Title = "GetMessages";
}

<h2>Messages</h2>

<table class="table">
    <tr>
        <th>Id</th>
        <th>Snippet</th>
    </tr>
@foreach (var message in Model.Messages) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => message.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => message.Title)
        </td>
    </tr>
}
</table>
@for (var i = 1; i <= Model.Pagination.TotalPagesCount; i++)
{
    if (Model.Pagination.PageNumber == i)
    {
        <a href="#" class="page-number active-page">@i</a>    
    }
    else
    {
        @Html.ActionLink(i.ToString(), "GetMessages", "Messages", new { pageNumber = i }, new { @class = "page-number" })
    }
}

GmailMessagesViewer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Messages", "GetMessages", "Messages")</li>
                </ul>
                @if (Session["User"] != null)
                {
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Change User", "ChangeUser", "Auth")</li>
                </ul>
                }
            </div>
            @*@if(Session[""])*@
            
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>